- name: daemon reload
  systemd:
    daemon_reload: yes
  tags: [ daemon_reload ]

- name: datanode start
  systemd: 
    state: started
    name: hdfs-datanode.service
  tags: [ start_datanode_service ]

- name: datanode enable
  systemd:
    name: hdfs-datanode.service
    enabled: yes
  tags: [ enable_datanode_service ]