- name: stop services and disable services
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
  with_items:
   - hdfs-zkfc.service
   - hdfs-namenode.service
   - hdfs-datanode.service
   - hdfs-journalnode.service
  ignore_errors: yes
  tags: [ remove_services ]

- name: remove all services
  file:
    path: "{{ item }}"
    state: absent
  with_items:
   - /etc/systemd/system/hdfs-zkfc.service
   - /etc/systemd/system/hdfs-namenode.service
   - /etc/systemd/system/hdfs-datanode.service
   - /etc/systemd/system/hdfs-journalnode.service
  ignore_errors: yes
  tags: [ remove_services_file ]

- name: remove hdfs tar.gz and home file
  file:
    path: "{{ item }}"
    state: absent
  with_items:
   - '{{ hdfs_unarchive_destination }}{{ hdfs_unarchived_filename }}.tar.gz'
   - '{{ hdfs_hadoop_home }}'
  tags: [ remove_dir_hdfs, remove_hdfs ]

- name: remove unused hosts from host file
  template:
    src: hosts.jinja2
    dest: /etc/hosts
    mode: 0640
  tags: [ remove_hosts_file, remove_hdfs ]

- name: remove dns
  lineinfile:
      path: /etc/resolv.conf
      line: 'nameserver {{ dns_server }}'
      state: absent
  tags: [ remove_dns ]

- name: check fuser installation
  apt:
    name: [psmisc, openjdk-8-jdk]
    state: absent
  tags: [ remove_apt ]