- block:
    - name: stop namenode services and disable namenode services
      systemd:
        name: "{{ item }}"
        state: stopped
        enabled: no
      with_items:
      - hdfs-zkfc.service
      - hdfs-namenode.service
      when: (ansible_default_ipv4.address in groups['namenodeservers'])
      tags: [ remove_services ]

    - name: remove namenode services
      file:
        path: "{{ item }}"
        state: absent
      with_items:
      - /etc/systemd/system/hdfs-zkfc.service
      - /etc/systemd/system/hdfs-namenode.service
      when: (ansible_default_ipv4.address in groups['namenodeservers'])
      tags: [ remove_services_file ]

    - name: stop datanode services and disable datanode services
      systemd:
        name: "{{ item }}"
        state: stopped
        enabled: no
      with_items:
      - hdfs-datanode.service
      when: (ansible_default_ipv4.address in groups['datanodeservers'])
      tags: [ remove_services ]

    - name: remove datanode services
      file:
        path: "{{ item }}"
        state: absent
      with_items:
      - /etc/systemd/system/hdfs-datanode.service
      when: (ansible_default_ipv4.address in groups['datanodeservers'])
      tags: [ remove_services_file ]

    - name: stop journalnode services and disable journalnode services
      systemd:
        name: "{{ item }}"
        state: stopped
        enabled: no
      with_items:
      - hdfs-journalnode.service
      when: (ansible_default_ipv4.address in groups['qjournalnodeservers'])
      tags: [ remove_services ]

    - name: remove journalnode services
      file:
        path: "{{ item }}"
        state: absent
      with_items:
      - /etc/systemd/system/hdfs-journalnode.service
      when: (ansible_default_ipv4.address in groups['qjournalnodeservers'])
      tags: [ remove_services_file ]
  ignore_errors: yes

- name: remove hdfs tar.gz and home file
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  #  - '{{ hdfs_unarchive_destination }}{{ hdfs_unarchived_filename }}.tar.gz'
   - '{{ hdfs_hadoop_home }}'
  tags: [ remove_dir_hdfs, remove_hdfs ]

- name: remove unused hosts from host file
  template:
    src: hosts.jinja2
    dest: /etc/hosts
    mode: 0640
  tags: [ remove_hosts_file, remove_hdfs ]

- name: remove dns
  lineinfile:
      path: /etc/resolv.conf
      line: 'nameserver {{ dns_server }}'
      state: absent
  tags: [ remove_dns ]

- name: check fuser installation
  apt:
    name: [ psmisc ]
    state: absent
  tags: [ remove_apt ]