- name: daemon reload
  systemd:
    daemon_reload: yes
  tags: [ daemon_reload ]

- name: journalnode restart
  systemd: 
    state: restarted
    name: hdfs-journalnode.service
  tags: [ start_journalnode_service ]

- name: journalnode enable
  systemd:
    name: hdfs-journalnode.service
    enabled: yes
  tags: [ enable_journalnode_service ]