- name: delete directories
  file:
    path: '{{ hdfs_dfs_journalnode_edits_dir }}/{{ hdfs_fs_defaultFS }}'
    state: absent
  tags: [ journalnode_dir ]

- name: create directories
  file:
    path: '{{ hdfs_dfs_journalnode_edits_dir }}/{{ hdfs_fs_defaultFS }}'
    state: directory
  tags: [ journalnode_dir ]

- name: create journalnode service
  template:
    src: hdfs-journalnode.service.j2
    dest: /etc/systemd/system/hdfs-journalnode.service
    mode: 0640
  notify:
   - daemon reload
   - journalnode restart
   - journalnode enable
  tags: [ add_service_journalnode ]